name: portfolio_rebalancer
description: A sophisticated fintech portfolio rebalancing app with RL-driven optimization

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1  
  google_fonts: ^6.1.0
  fl_chart: ^0.66.0
  shared_preferences: ^2.2.2
  http: ^1.2.0
  json_annotation: ^4.8.1
  animations: ^2.0.8
  cupertino_icons: ^1.0.6
  google_sign_in: ^6.1.5 # Use the latest version
  flutter_dotenv: ^5.1.0
  file_picker: ^5.2.5
  url_launcher: ^6.2.4
  webview_flutter: ^4.4.4
  share_plus: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  # No assets directory for now - Google Fonts will handle font loading
  assets:
    - assets/images/
    - assets/icons/
    - .env
    - assets/data/portfolio_full_seed.csv
  
  # Fonts (Google Fonts will handle font loading)
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter-Bold.ttf
          weight: 700